spring.application.name=gasto-hogar-api
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/gasto_hogar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=ricardo
spring.datasource.password=Ricardo16
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

springdoc.api-docs.path=/api/v1/docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

jwt.secret=ChangeThisSecretKeyToAtLeast32CharactersLong!
jwt.expiration=86400000

app.cors.allowed-origins=http://localhost:8100

logging.level.com.vjtech.gastoshogar=DEBUG
logging.level.org.springframework.security=WARN
logging.level.org.flywaydb=WARN